---
apiVersion: v1
kind: Namespace
metadata:
  name: ha
  labels:
    istio-injection: enabled
    # istio.io/rev: tsb-1-5-1-stable
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend
  namespace: ha
spec:
  secretName: frontend-cert
  issuerRef:
    name: letsencrypt-dns-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - demo.yellowstone.cx.tetrate.info
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: frontend-gateway
  namespace: ha
spec:
  revision: tsb-1-5-1-stable
  kubeSpec:
    service:
      type: LoadBalancer
      annotations:
        "external-dns.alpha.kubernetes.io/hostname": "demo.yellowstone.cx.tetrate.info."
        "external-dns.alpha.kubernetes.io/alias": "true"
        "external-dns.alpha.kubernetes.io/set-identifier": "frontend-east"
        "external-dns.alpha.kubernetes.io/aws-region": "us-east-2"
        "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"